### ISSUE TITLE
Incompatibilite safari

### ISSUE THREAD

**Issue by loichu** [epfl-enacit2/epfl-formApprentis#1]
Hello, 
Ma mere (utilisatrice standard) a presque abandonne le remplissage du formulaire si je n'avais pas été la.

Il est impossible d'importer des fichiers depuis Safari, les utilisateurs ne changent pas de navigateur, ils changent de site.

J'apporte volontiers mon aide si besoin.
Cordialement, loichu

**Comment by nicrausaz** [comment]
Les incompatibilités safari (requireds et inputs type file) ont été corrigées.

Merci d'avoir signalé les problèmes.
