### ISSUE TITLE
Format jpg mal supporte

### ISSUE THREAD

**Issue by loichu** [epfl-enacit2/epfl-formApprentis#2]
Hello, 
Ma mere (utilisatrice standard) a presque abandonne le remplissage du formulaire si je n'avais pas été la.

Le format jpg n'est pas reconnu si l'extension de fichier est en majuscule. C'est certainement aussi le cas pour les autres formats. Le cas du jpg est plus ennuyant car certains smartphones enregistrent en JPG.

J'apporte volontiers mon aide si besoin.
Cordialement, loichu

**Comment by loichu** [comment]
Corrected !

**Comment by nicrausaz** [comment]
Le format jpg et les formats en majuscules sont maintenant supportés.

Merci d'avoir signalé les problèmes.
