### ISSUE TITLE
Human errors handling

### ISSUE THREAD

**Issue by loichu** [epfl-enacit2/epfl-formApprentis#4]
Lorsqu'on rempli le formulaire en entier, que le javascript nous a prévenu d'aucune erreur, qu'on tombe sur un message d'erreur comme ci-joint et qu'en revenant sur le formulaire on doit tout reremplir.... RAAAAGE.

Heureusement je suis là pour t'aider à rendre la postulation des apprenti un peu plus agréable.
![thanks](https://cloud.githubusercontent.com/assets/14270237/23075410/aa67fc7c-f53c-11e6-8516-4eb2236706a4.png)

**Comment by nicrausaz** [comment]
Les erreurs sont maintenant affichées sous forme de liste, les phrases sont maintenant en français lisible...

Merci d'avoir signalé les problèmes.
